name: CI for VDC-bundles

on: push

jobs:
  vm-job:
    runs-on: ubuntu-latest

    container:
      image: maven:3-jdk-8

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --name postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

      - name: Install docker CLI
        run: |
         export DEBIAN_FRONTEND=noninteractive;
         apt-get update -y;
         curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -;
         apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common;
         add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable";
         apt-get update -y;
         apt-get install -y docker-ce-cli;


      - name: check db setting
        run : |
          set -xe;
          docker ps
          docker exec -u postgres $POSTGRES_CONTAINER /usr/bin/psql -c "SHOW max_connections;"
          set +xe;
        env:
          POSTGRES_CONTAINER: postgres


